// This file was automatically generated by make-pins.py
//
// --af boards/stm32f303_af.csv
// --board boards/STM32F3DISC/pins.csv
// --prefix boards/stm32f4xx_prefix.c

// stm32f4xx_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
    { \
        { &pin_af_type }, \
        .name = MP_QSTR_AF##af_idx##_##af_fn##af_unit, \
        .idx = (af_idx), \
        .fn = AF_FN_##af_fn, \
        .unit = (af_unit), \
        .type = AF_PIN_TYPE_##af_fn##_##af_type, \
        .reg = (af_ptr) \
    }

#define PIN(p_port, p_pin, p_af, p_adc_num, p_adc_channel) \
    { \
        { &pin_type }, \
        .name = MP_QSTR_##p_port##p_pin, \
        .port = PORT_##p_port, \
        .pin = (p_pin), \
        .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
        .pin_mask = (1 << ((p_pin) & 0x0f)), \
        .gpio = GPIO##p_port, \
        .af = p_af, \
        .adc_num = p_adc_num, \
        .adc_channel = p_adc_channel, \
    }

const pin_af_obj_t pin_A0_af[] = {
  AF( 1, TIM     ,  2, CH1_ETR   , TIM2    ), // TIM2_CH1_ETR
  //( 3, TSC     ,  0, G1_IO1    , TSC     ), // TSC_G1_IO1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CTS       , USART2  ), // USART2_CTS
#endif
  //( 8, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
  AF( 9, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  AF(10, TIM     ,  8, ETR       , TIM8    ), // TIM8_ETR
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A0_obj = PIN(A, 0, pin_A0_af, PIN_ADC1, 1);

const pin_af_obj_t pin_A1_af[] = {
  //( 0, RTC     ,  0, REFIN     , RTC     ), // RTC_REFIN
  AF( 1, TIM     ,  2, CH2       , TIM2    ), // TIM2_CH2
  //( 3, TSC     ,  0, G1_IO2    , TSC     ), // TSC_G1_IO2
  //( 7, USART   ,  2, RTS_DE    , USART2  ), // USART2_RTS_DE
  AF( 9, TIM     , 15, CH1N      , TIM15   ), // TIM15_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A1_obj = PIN(A, 1, pin_A1_af, PIN_ADC1, 2);

const pin_af_obj_t pin_A2_af[] = {
  AF( 1, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
  //( 3, TSC     ,  0, G1_IO3    , TSC     ), // TSC_G1_IO3
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
  //( 8, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
  AF( 9, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A2_obj = PIN(A, 2, pin_A2_af, PIN_ADC1, 3);

const pin_af_obj_t pin_A3_af[] = {
  AF( 1, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
  //( 3, TSC     ,  0, G1_IO4    , TSC     ), // TSC_G1_IO4
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  AF( 9, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A3_obj = PIN(A, 3, pin_A3_af, PIN_ADC1, 4);

const pin_af_obj_t pin_A4_af[] = {
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  //( 3, TSC     ,  0, G2_IO1    , TSC     ), // TSC_G2_IO1
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
  //( 6, I2S3WS  ,  0,           , I2S3WS  ), // I2S3WS
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A4_obj = PIN(A, 4, pin_A4_af, PIN_ADC2, 1);

const pin_af_obj_t pin_A5_af[] = {
  AF( 1, TIM     ,  2, CH1_ETR   , TIM2    ), // TIM2_CH1_ETR
  //( 3, TSC     ,  0, G2_IO2    , TSC     ), // TSC_G2_IO2
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A5_obj = PIN(A, 5, pin_A5_af, PIN_ADC2, 2);

const pin_af_obj_t pin_A6_af[] = {
  AF( 1, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  //( 3, TSC     ,  0, G2_IO3    , TSC     ), // TSC_G2_IO3
  AF( 4, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  AF( 6, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  //( 8, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A6_obj = PIN(A, 6, pin_A6_af, PIN_ADC2, 3);

const pin_af_obj_t pin_A7_af[] = {
  AF( 1, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  //( 3, TSC     ,  0, G2_IO4    , TSC     ), // TSC_G2_IO4
  AF( 4, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  AF( 6, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
  //( 8, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A7_obj = PIN(A, 7, pin_A7_af, PIN_ADC2, 4);

const pin_af_obj_t pin_A8_af[] = {
  //( 0, MCO     ,  0,           , MCO     ), // MCO
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, MCK       , I2S2    ), // I2S2_MCK
#endif
  AF( 6, TIM     ,  1, CH1       , TIM1    ), // TIM1_CH1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CK        , USART1  ), // USART1_CK
#endif
  //( 8, COMP    ,  3, OUT       , COMP3   ), // COMP3_OUT
  AF(10, TIM     ,  4, ETR       , TIM4    ), // TIM4_ETR
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A8_obj = PIN(A, 8, pin_A8_af, 0, 0);

const pin_af_obj_t pin_A9_af[] = {
  //( 3, TSC     ,  0, G4_IO1    , TSC     ), // TSC_G4_IO1
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 5, I2S     ,  3, MCK       , I2S3    ), // I2S3_MCK
#endif
  AF( 6, TIM     ,  1, CH2       , TIM1    ), // TIM1_CH2
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //( 8, COMP    ,  5, OUT       , COMP5   ), // COMP5_OUT
  AF( 9, TIM     , 15, BKIN      , TIM15   ), // TIM15_BKIN
  AF(10, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A9_obj = PIN(A, 9, pin_A9_af, 0, 0);

const pin_af_obj_t pin_A10_af[] = {
  AF( 1, TIM     , 17, BKIN      , TIM17   ), // TIM17_BKIN
  //( 3, TSC     ,  0, G4_IO2    , TSC     ), // TSC_G4_IO2
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
  AF( 6, TIM     ,  1, CH3       , TIM1    ), // TIM1_CH3
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
  //( 8, COMP    ,  6, OUT       , COMP6   ), // COMP6_OUT
  AF(10, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
  AF(11, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A10_obj = PIN(A, 10, pin_A10_af, 0, 0);

const pin_af_obj_t pin_A11_af[] = {
  AF( 6, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CTS       , USART1  ), // USART1_CTS
#endif
  //( 8, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  AF(10, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
  AF(11, TIM     ,  1, CH4       , TIM1    ), // TIM1_CH4
  //(12, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
  //(14, USB     ,  0, DM        , USB     ), // USB_DM
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A11_obj = PIN(A, 11, pin_A11_af, 0, 0);

const pin_af_obj_t pin_A12_af[] = {
  AF( 1, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  AF( 6, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  //( 7, USART   ,  1, RTS_DE    , USART1  ), // USART1_RTS_DE
  //( 8, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  AF(10, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
  AF(11, TIM     ,  1, ETR       , TIM1    ), // TIM1_ETR
  //(14, USB     ,  0, DP        , USB     ), // USB_DP
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A12_obj = PIN(A, 12, pin_A12_af, 0, 0);

const pin_af_obj_t pin_A13_af[] = {
  //( 0, SWDIO   ,  0,           , SWDIO   ), // SWDIO
  //( 0, JTMS    ,  0,           , JTMS    ), // JTMS
  AF( 1, TIM     , 16, CH1N      , TIM16   ), // TIM16_CH1N
  //( 3, TSC     ,  0, G4_IO3    , TSC     ), // TSC_G4_IO3
  //( 5, IR      ,  0, OUT       , IR      ), // IR_OUT
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CTS       , USART3  ), // USART3_CTS
#endif
  AF(10, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A13_obj = PIN(A, 13, pin_A13_af, 0, 0);

const pin_af_obj_t pin_A14_af[] = {
  //( 0, SWCLK   ,  0,           , SWCLK   ), // SWCLK
  //( 0, JTCK    ,  0,           , JTCK    ), // JTCK
  //( 3, TSC     ,  0, G4_IO4    , TSC     ), // TSC_G4_IO4
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
  AF( 5, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
  AF( 6, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A14_obj = PIN(A, 14, pin_A14_af, 0, 0);

const pin_af_obj_t pin_A15_af[] = {
  //( 0, JTDI    ,  0,           , JTDI    ), // JTDI
  AF( 1, TIM     ,  2, CH1_ETR   , TIM2    ), // TIM2_CH1_ETR
  AF( 2, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, WS        , I2S3    ), // I2S3_WS
#endif
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  AF( 9, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A15_obj = PIN(A, 15, pin_A15_af, 0, 0);

const pin_af_obj_t pin_B0_af[] = {
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  //( 3, TSC     ,  0, G3_IO2    , TSC     ), // TSC_G3_IO2
  AF( 4, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
  AF( 6, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B0_obj = PIN(B, 0, pin_B0_af, PIN_ADC3, 12);

const pin_af_obj_t pin_B1_af[] = {
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  //( 3, TSC     ,  0, G3_IO3    , TSC     ), // TSC_G3_IO3
  AF( 4, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
  AF( 6, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
  //( 8, COMP    ,  4, OUT       , COMP4   ), // COMP4_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B1_obj = PIN(B, 1, pin_B1_af, PIN_ADC3, 1);

// const pin_af_obj_t pin_B2_af[] = {
  //( 3, TSC     ,  0, G3_IO4    , TSC     ), // TSC_G3_IO4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_B2_obj = PIN(B, 2, NULL, PIN_ADC2, 12);

const pin_af_obj_t pin_B4_af[] = {
  //( 0, NJTRST  ,  0,           , NJTRST  ), // NJTRST
  AF( 1, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  //( 3, TSC     ,  0, G5_IO2    , TSC     ), // TSC_G5_IO2
  AF( 4, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, EXTSD     , I2S3    ), // I2S3_EXTSD
#endif
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  AF(10, TIM     , 17, BKIN      , TIM17   ), // TIM17_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B4_obj = PIN(B, 4, pin_B4_af, 0, 0);

const pin_af_obj_t pin_B5_af[] = {
  AF( 1, TIM     , 16, BKIN      , TIM16   ), // TIM16_BKIN
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  AF( 3, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, SD        , I2S3    ), // I2S3_SD
#endif
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
  AF(10, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B5_obj = PIN(B, 5, pin_B5_af, 0, 0);

const pin_af_obj_t pin_B6_af[] = {
  AF( 1, TIM     , 16, CH1N      , TIM16   ), // TIM16_CH1N
  AF( 2, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
  //( 3, TSC     ,  0, G5_IO3    , TSC     ), // TSC_G5_IO3
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
  AF( 5, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
  AF( 6, TIM     ,  8, ETR       , TIM8    ), // TIM8_ETR
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //(10, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B6_obj = PIN(B, 6, pin_B6_af, 0, 0);

const pin_af_obj_t pin_B7_af[] = {
  AF( 1, TIM     , 17, CH1N      , TIM17   ), // TIM17_CH1N
  AF( 2, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
  //( 3, TSC     ,  0, G5_IO4    , TSC     ), // TSC_G5_IO4
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
  AF( 5, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
  AF(10, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B7_obj = PIN(B, 7, pin_B7_af, 0, 0);

const pin_af_obj_t pin_B8_af[] = {
  AF( 1, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  AF( 2, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //( 3, TSC     ,  0, SYNC      , TSC     ), // TSC_SYNC
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
  //( 8, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  AF(10, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
  AF(12, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B8_obj = PIN(B, 8, pin_B8_af, 0, 0);

const pin_af_obj_t pin_B9_af[] = {
  AF( 1, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  AF( 2, TIM     ,  4, CH4       , TIM4    ), // TIM4_CH4
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
  //( 6, IR      ,  0, OUT       , IR      ), // IR_OUT
  //( 8, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  AF(10, TIM     ,  8, CH3       , TIM8    ), // TIM8_CH3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B9_obj = PIN(B, 9, pin_B9_af, 0, 0);

const pin_af_obj_t pin_B10_af[] = {
  AF( 1, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
  //( 3, TSC     ,  0, SYNC      , TSC     ), // TSC_SYNC
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B10_obj = PIN(B, 10, pin_B10_af, 0, 0);

const pin_af_obj_t pin_B11_af[] = {
  AF( 1, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
  //( 3, TSC     ,  0, G6_IO1    , TSC     ), // TSC_G6_IO1
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B11_obj = PIN(B, 11, pin_B11_af, 0, 0);

const pin_af_obj_t pin_B12_af[] = {
  //( 3, TSC     ,  0, G6_IO2    , TSC     ), // TSC_G6_IO2
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, WS        , I2S2    ), // I2S2_WS
#endif
  AF( 6, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B12_obj = PIN(B, 12, pin_B12_af, 0, 3);

const pin_af_obj_t pin_B13_af[] = {
  //( 3, TSC     ,  0, G6_IO3    , TSC     ), // TSC_G6_IO3
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, CK        , I2S2    ), // I2S2_CK
#endif
  AF( 6, TIM     ,  0, CH1N      , TIM     ), // TIM_CH1N
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CTS       , USART3  ), // USART3_CTS
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B13_obj = PIN(B, 13, pin_B13_af, PIN_ADC3, 5);

const pin_af_obj_t pin_B14_af[] = {
  AF( 1, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  AF( 2, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //( 3, TSC     ,  0, G6_IO4    , TSC     ), // TSC_G6_IO4
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, EXTSD     , I2S2    ), // I2S2_EXTSD
#endif
  AF( 6, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B14_obj = PIN(B, 14, pin_B14_af, 0, 3);

const pin_af_obj_t pin_B15_af[] = {
  //( 0, RTC     ,  0, REFIN     , RTC     ), // RTC_REFIN
  AF( 1, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  AF( 2, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  AF( 4, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
#if defined(MICROPY_HW_I2S2)
  AF( 5, I2S     ,  2, SD        , I2S2    ), // I2S2_SD
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B15_obj = PIN(B, 15, pin_B15_af, 0, 5);

// const pin_af_obj_t pin_C0_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C0_obj = PIN(C, 0, NULL, PIN_ADC1 | PIN_ADC2, 6);

// const pin_af_obj_t pin_C1_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C1_obj = PIN(C, 1, NULL, PIN_ADC1 | PIN_ADC2, 7);

// const pin_af_obj_t pin_C2_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  //( 3, COMP    ,  7, OUT       , COMP7   ), // COMP7_OUT
// };

const pin_obj_t pin_C2_obj = PIN(C, 2, NULL, PIN_ADC1 | PIN_ADC2, 8);

// const pin_af_obj_t pin_C3_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  //( 6, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
// };

const pin_obj_t pin_C3_obj = PIN(C, 3, NULL, PIN_ADC1 | PIN_ADC2, 9);

const pin_af_obj_t pin_C4_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
};

const pin_obj_t pin_C4_obj = PIN(C, 4, pin_C4_af, PIN_ADC2, 5);

const pin_af_obj_t pin_C5_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  //( 3, TSC     ,  0, G3_IO1    , TSC     ), // TSC_G3_IO1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
};

const pin_obj_t pin_C5_obj = PIN(C, 5, pin_C5_af, PIN_ADC2, 11);

const pin_af_obj_t pin_C6_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  AF( 4, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
#if defined(MICROPY_HW_I2S2)
  AF( 6, I2S     ,  2, MCK       , I2S2    ), // I2S2_MCK
#endif
  //( 7, COMP    ,  6, OUT       , COMP6   ), // COMP6_OUT
};

const pin_obj_t pin_C6_obj = PIN(C, 6, pin_C6_af, 0, 0);

const pin_af_obj_t pin_C7_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  AF( 4, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, MCK       , I2S3    ), // I2S3_MCK
#endif
  //( 7, COMP    ,  5, OUT       , COMP5   ), // COMP5_OUT
};

const pin_obj_t pin_C7_obj = PIN(C, 7, pin_C7_af, 0, 0);

const pin_af_obj_t pin_C8_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  AF( 4, TIM     ,  8, CH3       , TIM8    ), // TIM8_CH3
  //( 7, COMP    ,  3, OUT       , COMP3   ), // COMP3_OUT
};

const pin_obj_t pin_C8_obj = PIN(C, 8, pin_C8_af, 0, 0);

const pin_af_obj_t pin_C9_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  AF( 4, TIM     ,  8, CH4       , TIM8    ), // TIM8_CH4
  //( 5, I2S     ,  0, CKIN      , I2S     ), // I2S_CKIN
  //( 6, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
};

const pin_obj_t pin_C9_obj = PIN(C, 9, pin_C9_af, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 4, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
#if defined(MICROPY_HW_UART4_TX)
  AF( 5, UART    ,  4, TX        , UART4   ), // UART4_TX
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, CK        , I2S3    ), // I2S3_CK
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
};

const pin_obj_t pin_C10_obj = PIN(C, 10, pin_C10_af, 0, 0);

const pin_af_obj_t pin_C11_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 4, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
#if defined(MICROPY_HW_UART4_TX)
  AF( 5, UART    ,  4, RX        , UART4   ), // UART4_RX
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, EXTSD     , I2S3    ), // I2S3_EXTSD
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
};

const pin_obj_t pin_C11_obj = PIN(C, 11, pin_C11_af, 0, 0);

const pin_af_obj_t pin_C12_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 4, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
#if defined(MICROPY_HW_UART5_TX)
  AF( 5, UART    ,  5, TX        , UART5   ), // UART5_TX
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_I2S3)
  AF( 6, I2S     ,  3, SD        , I2S3    ), // I2S3_SD
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
};

const pin_obj_t pin_C12_obj = PIN(C, 12, pin_C12_af, 0, 0);

const pin_af_obj_t pin_C13_af[] = {
  AF( 4, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
};

const pin_obj_t pin_C13_obj = PIN(C, 13, pin_C13_af, 0, 0);

// const pin_af_obj_t pin_C14_af[] = {
// };

const pin_obj_t pin_C14_obj = PIN(C, 14, NULL, 0, 0);

// const pin_af_obj_t pin_C15_af[] = {
// };

const pin_obj_t pin_C15_obj = PIN(C, 15, NULL, 0, 0);

const pin_af_obj_t pin_D0_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_CAN1_TX)
  AF( 7, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
};

const pin_obj_t pin_D0_obj = PIN(D, 0, pin_D0_af, 0, 0);

const pin_af_obj_t pin_D1_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 4, TIM     ,  8, CH4       , TIM8    ), // TIM8_CH4
  //( 6, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
#if defined(MICROPY_HW_CAN1_TX)
  AF( 7, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
};

const pin_obj_t pin_D1_obj = PIN(D, 1, pin_D1_af, 0, 0);

const pin_af_obj_t pin_D2_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, ETR       , TIM3    ), // TIM3_ETR
  AF( 4, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
#if defined(MICROPY_HW_UART5_TX)
  AF( 5, UART    ,  5, RX        , UART5   ), // UART5_RX
#endif
};

const pin_obj_t pin_D2_obj = PIN(D, 2, pin_D2_af, 0, 0);

const pin_af_obj_t pin_D3_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  2, CH1_ETR   , TIM2    ), // TIM2_CH1_ETR
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CTS       , USART2  ), // USART2_CTS
#endif
};

const pin_obj_t pin_D3_obj = PIN(D, 3, pin_D3_af, 0, 0);

const pin_af_obj_t pin_D4_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  2, CH2       , TIM2    ), // TIM2_CH2
  //( 7, USART   ,  2, RTS_DE    , USART2  ), // USART2_RTS_DE
};

const pin_obj_t pin_D4_obj = PIN(D, 4, pin_D4_af, 0, 0);

const pin_af_obj_t pin_D5_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
};

const pin_obj_t pin_D5_obj = PIN(D, 5, pin_D5_af, 0, 0);

const pin_af_obj_t pin_D6_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
};

const pin_obj_t pin_D6_obj = PIN(D, 6, pin_D6_af, 0, 0);

const pin_af_obj_t pin_D7_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
};

const pin_obj_t pin_D7_obj = PIN(D, 7, pin_D7_af, 0, 0);

const pin_af_obj_t pin_D8_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
};

const pin_obj_t pin_D8_obj = PIN(D, 8, pin_D8_af, 0, 12);

const pin_af_obj_t pin_D9_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
};

const pin_obj_t pin_D9_obj = PIN(D, 9, pin_D9_af, 0, 13);

const pin_af_obj_t pin_D10_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
};

const pin_obj_t pin_D10_obj = PIN(D, 10, pin_D10_af, PIN_ADC3, 7);

const pin_af_obj_t pin_D11_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CTS       , USART3  ), // USART3_CTS
#endif
};

const pin_obj_t pin_D11_obj = PIN(D, 11, pin_D11_af, PIN_ADC3, 8);

const pin_af_obj_t pin_D12_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
  //( 3, TSC     ,  0, G8_IO1    , TSC     ), // TSC_G8_IO1
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
};

const pin_obj_t pin_D12_obj = PIN(D, 12, pin_D12_af, PIN_ADC3, 9);

const pin_af_obj_t pin_D13_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
  //( 3, TSC     ,  0, G8_IO2    , TSC     ), // TSC_G8_IO2
};

const pin_obj_t pin_D13_obj = PIN(D, 13, pin_D13_af, PIN_ADC3, 10);

const pin_af_obj_t pin_D14_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //( 3, TSC     ,  0, G8_IO3    , TSC     ), // TSC_G8_IO3
};

const pin_obj_t pin_D14_obj = PIN(D, 14, pin_D14_af, PIN_ADC3, 11);

const pin_af_obj_t pin_D15_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  4, CH4       , TIM4    ), // TIM4_CH4
  //( 3, TSC     ,  0, G8_IO4    , TSC     ), // TSC_G8_IO4
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 6, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
};

const pin_obj_t pin_D15_obj = PIN(D, 15, pin_D15_af, 0, 0);

const pin_af_obj_t pin_E0_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  4, ETR       , TIM4    ), // TIM4_ETR
  AF( 4, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
};

const pin_obj_t pin_E0_obj = PIN(E, 0, pin_E0_af, 0, 0);

const pin_af_obj_t pin_E1_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 4, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
};

const pin_obj_t pin_E1_obj = PIN(E, 1, pin_E1_af, 0, 0);

const pin_af_obj_t pin_E2_af[] = {
  //( 0, TRACECK ,  0,           , TRACECK ), // TRACECK
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  //( 3, TSC     ,  0, G7_IO1    , TSC     ), // TSC_G7_IO1
};

const pin_obj_t pin_E2_obj = PIN(E, 2, pin_E2_af, 0, 0);

const pin_af_obj_t pin_E3_af[] = {
  //( 0, TRACED  ,  0,           , TRACED0 ), // TRACED0
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  //( 3, TSC     ,  0, G7_IO2    , TSC     ), // TSC_G7_IO2
};

const pin_obj_t pin_E3_obj = PIN(E, 3, pin_E3_af, 0, 0);

const pin_af_obj_t pin_E4_af[] = {
  //( 0, TRACED  ,  1,           , TRACED1 ), // TRACED1
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  //( 3, TSC     ,  0, G7_IO3    , TSC     ), // TSC_G7_IO3
};

const pin_obj_t pin_E4_obj = PIN(E, 4, pin_E4_af, 0, 0);

const pin_af_obj_t pin_E5_af[] = {
  //( 0, TRACED  ,  2,           , TRACED2 ), // TRACED2
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  //( 3, TSC     ,  0, G7_IO4    , TSC     ), // TSC_G7_IO4
};

const pin_obj_t pin_E5_obj = PIN(E, 5, pin_E5_af, 0, 0);

// const pin_af_obj_t pin_E6_af[] = {
  //( 0, TRACED  ,  3,           , TRACED3 ), // TRACED3
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_E6_obj = PIN(E, 6, NULL, 0, 0);

const pin_af_obj_t pin_E7_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, ETR       , TIM1    ), // TIM1_ETR
};

const pin_obj_t pin_E7_obj = PIN(E, 7, pin_E7_af, PIN_ADC3, 13);

const pin_af_obj_t pin_E8_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
};

const pin_obj_t pin_E8_obj = PIN(E, 8, pin_E8_af, PIN_ADC3, 6);

const pin_af_obj_t pin_E9_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH1       , TIM1    ), // TIM1_CH1
};

const pin_obj_t pin_E9_obj = PIN(E, 9, pin_E9_af, PIN_ADC3, 2);

const pin_af_obj_t pin_E10_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
};

const pin_obj_t pin_E10_obj = PIN(E, 10, pin_E10_af, PIN_ADC3, 14);

const pin_af_obj_t pin_E11_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH2       , TIM1    ), // TIM1_CH2
};

const pin_obj_t pin_E11_obj = PIN(E, 11, pin_E11_af, PIN_ADC3, 15);

const pin_af_obj_t pin_E12_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
};

const pin_obj_t pin_E12_obj = PIN(E, 12, pin_E12_af, PIN_ADC3, 16);

const pin_af_obj_t pin_E13_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH3       , TIM1    ), // TIM1_CH3
};

const pin_obj_t pin_E13_obj = PIN(E, 13, pin_E13_af, PIN_ADC3, 3);

const pin_af_obj_t pin_E14_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, CH4       , TIM1    ), // TIM1_CH4
  //( 6, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
};

const pin_obj_t pin_E14_obj = PIN(E, 14, pin_E14_af, 0, 1);

const pin_af_obj_t pin_E15_af[] = {
  //( 1, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
  AF( 2, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
};

const pin_obj_t pin_E15_obj = PIN(E, 15, pin_E15_af, 0, 2);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_A4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_A5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_A6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_A7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_A8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_A9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_A10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_A11), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_A12), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_A13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_A14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_A15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_B0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_B1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_B2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_B4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_B5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_B6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_B7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_B8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_B9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_B10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_B11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_B12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_B13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_B14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_B15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_C0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_C1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_C2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_C3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_C4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_C5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_C6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_C7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_C8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_C9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_C10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_C11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_C12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_C13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_C14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_C15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_D0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_D14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_D15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_E0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_E1), MP_ROM_PTR(&pin_E1_obj) },
  { MP_ROM_QSTR(MP_QSTR_E2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_E3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_E4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_E5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_E6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_E7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_E8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_E9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_E10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_E11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_E12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_E13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_E14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_E15), MP_ROM_PTR(&pin_E15_obj) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_PC0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE1), MP_ROM_PTR(&pin_E1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_LED_GREEN), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_LED_ORANGE), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_LED_RED), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_LED_BLUE), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_SW), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_USB_DM), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_USB_DP), MP_ROM_PTR(&pin_A12_obj) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[10] = {
  [0] = NULL,
  [1] = &pin_A0_obj,
  [2] = &pin_A1_obj,
  [3] = &pin_A2_obj,
  [4] = &pin_A3_obj,
  [5] = NULL,
  [6] = &pin_C0_obj,
  [7] = &pin_C1_obj,
  [8] = &pin_C2_obj,
  [9] = &pin_C3_obj,
};

const pin_obj_t * const pin_adc2[13] = {
  [0] = NULL,
  [1] = &pin_A4_obj,
  [2] = &pin_A5_obj,
  [3] = &pin_A6_obj,
  [4] = &pin_A7_obj,
  [5] = &pin_C4_obj,
  [6] = &pin_C0_obj,
  [7] = &pin_C1_obj,
  [8] = &pin_C2_obj,
  [9] = &pin_C3_obj,
  [10] = NULL,
  [11] = &pin_C5_obj,
  [12] = &pin_B2_obj,
};

const pin_obj_t * const pin_adc3[17] = {
  [0] = NULL,
  [1] = &pin_B1_obj,
  [2] = &pin_E9_obj,
  [3] = &pin_E13_obj,
  [4] = NULL,
  [5] = &pin_B13_obj,
  [6] = &pin_E8_obj,
  [7] = &pin_D10_obj,
  [8] = &pin_D11_obj,
  [9] = &pin_D12_obj,
  [10] = &pin_D13_obj,
  [11] = &pin_D14_obj,
  [12] = &pin_B0_obj,
  [13] = &pin_E7_obj,
  [14] = &pin_E10_obj,
  [15] = &pin_E11_obj,
  [16] = &pin_E12_obj,
};
